
# Set variables

# determines OS behavior
export OS_TYPE=`uname -s` 

# source helper functions
source "${HOME}"/.init-functions.bash

# Load supplementary scripts
for config in "$HOME"/.bashrc.d/*.bash ; do
	source "$config"
done
unset -v config

if [ -f ~/.bashrc_local ]; then
	. ~/.bashrc_local
fi
